@protocoll=http
@host=scan.rpi
@port=7575
@device=genesys:libusb:001:004

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json
Accept: image/png

{
    "Device":"{{device}}",
    "Options":{"resolution":300}
}

###

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{
    "Device":"{{device}}",
    "Options":{"resolution":300}
}

###

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{
    "Device":"{{device}}",
    "Options":{"resolution":500000}
}

###

GET {{protocoll}}://{{host}}:{{port}}/ HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/list HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/last HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/last HTTP/1.1
Accept: image/png

###
GET {{protocoll}}://{{host}}:{{port}}/last?scan= HTTP/1.1
Accept: image/png

###

GET {{protocoll}}://{{host}}:{{port}}/config?device={{device}} HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/config?device=foobar HTTP/1.1