@protocoll=http
@host=scan.rpi
@port=7575
@device=genesys:libusb:001:006

###

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{
    "Device":"{{device}}",
    "Options":{"resolution":150}
}

###
# DIN A4 - simple

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{
    "Device":"{{device}}",
    "Options":{"resolution":150,"br-y":297,"br-x":210,"tl-y":0,"tl-x":0}
}


###

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{"Device":"genesys:libusb:001:004","Options":{"br-y":0,"br-x":0,"tl-y":297.5,"tl-x":216.0}}


###

POST {{protocoll}}://{{host}}:{{port}}/scan HTTP/1.1
content-type: application/json

{
    "Device":"{{device}}",
    "Options":{"resolution":500000}
}

###

GET {{protocoll}}://{{host}}:{{port}}/ HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/list HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/last HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/config?device={{device}} HTTP/1.1

###

GET {{protocoll}}://{{host}}:{{port}}/config?device=foobar HTTP/1.1